services:
  - type: web
    name: bill-organizer-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install && node --input-type=module -e "import('tesseract.js').then(m => m.createWorker('eng+mya'))"
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://phyat-paing-gktvzhj8d-vimmms-projects.vercel.app
